import { ReactNode } from 'react'
import './globals.css'
import { Didact_Gothic, Saira_Stencil_One } from 'next/font/google'

const didact = Didact_Gothic({
  weight: '400',
  preload: false,
  variable: '--font-didact',
})

const saira = Saira_Stencil_One({
  weight: ['400'],
  preload: false,
  variable: '--font-saira',
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${didact.variable} ${saira.variable}`}>
      <body>{children}</body>
    </html>
  )
}
