import './globals.css'
import { Didact_Gothic } from 'next/font/google'

const didact = Didact_Gothic({
  weight: '400',
  preload: false,
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={didact.className}>{children}</body>
    </html>
  )
}
